modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/scientianovateam/Versatile/issues"
[[mods]]
modId="versatile"
version="${file.jarVersion}"
displayName="Versatile"
logoFile="versatile.png"
authors="TheEmosewaPixel, Quantum64"
description="A mod for adding a large number of items, blocks, fluids, machines and more through a data-driven system."
[[dependencies.versatile]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.versatile]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.versatile]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.25,)"
    ordering="AFTER"
    side="BOTH"