modLoader="javafml" #mandatory
loaderVersion="[27,)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="pixellib"
version="${file.jarVersion}"
displayName="Pixel Lib"
authors="TheEmosewaPixel"
description="A library mod for easily adding some new things"
[[dependencies.pixellib]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixellib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixellib]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.2,)"
    ordering="AFTER"
    side="BOTH"