modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/scientianovateam/Versatile/issues"
[[mods]]
modId="versatile"
version="${file.jarVersion}"
displayName="Versatile"
logoFile="versatile.png"
authors="TheEmosewaPixel"
description="A library mod for easily adding some new things"
[[dependencies.versatile]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.versatile]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.versatile]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.25,)"
    ordering="AFTER"
    side="BOTH"