modLoader="kotlinfml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/EmosewaPixel/PixelLib/issues"
[[mods]]
modId="pixellib"
version="${file.jarVersion}"
displayName="Pixel Lib"
logoFile="pixellib.png"
authors="TheEmosewaPixel"
description="A library mod for easily adding some new things"
[[dependencies.pixellib]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixellib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.pixellib]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.8,)"
    ordering="AFTER"
    side="BOTH"